services:
  postgres:
    image: postgres:16-alpine
    container_name: cooksnap-db
    environment:
      POSTGRES_USER: cooksnap
      POSTGRES_PASSWORD: cooksnap
      POSTGRES_DB: cooksnap_dev
    ports:
      - '5433:5432'
    volumes:
      - cooksnap_pgdata:/var/lib/postgresql/data

volumes:
  cooksnap_pgdata:
